name: test

on: push

jobs:
  test:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: yarn install
      - name: Run Docker container
        run: docker compose up server & ORIGIN=http://localhost:8080 yarn test
